//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Configuración: {0}.
        /// </summary>
        internal static string ConfError {
            get {
                return ResourceManager.GetString("ConfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to día.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to días.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entre las {0} y las {1}.
        /// </summary>
        internal static string EventDescDailyLimits {
            get {
                return ResourceManager.GetString("EventDescDailyLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el día {0} de .
        /// </summary>
        internal static string EventDescDayOfMonth {
            get {
                return ResourceManager.GetString("EventDescDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasta el {0}.
        /// </summary>
        internal static string EventDescLimitsEnd {
            get {
                return ResourceManager.GetString("EventDescLimitsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comenzando el {0}.
        /// </summary>
        internal static string EventDescLimitsStart {
            get {
                return ResourceManager.GetString("EventDescLimitsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el {0} {1} de .
        /// </summary>
        internal static string EventDescMonthFrecuency {
            get {
                return ResourceManager.GetString("EventDescMonthFrecuency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre una única vez..
        /// </summary>
        internal static string EventDescOnce {
            get {
                return ResourceManager.GetString("EventDescOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cada {0} {1}.
        /// </summary>
        internal static string EventDescRecurringEvery {
            get {
                return ResourceManager.GetString("EventDescRecurringEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a las {0}.
        /// </summary>
        internal static string EventDescRecurringHour {
            get {
                return ResourceManager.GetString("EventDescRecurringHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre .
        /// </summary>
        internal static string EventDescRecurringStart {
            get {
                return ResourceManager.GetString("EventDescRecurringStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el {0}.
        /// </summary>
        internal static string EventDescRecurringWeekly {
            get {
                return ResourceManager.GetString("EventDescRecurringWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programado para el {0} a las {1}.
        /// </summary>
        internal static string EventDescSchedule {
            get {
                return ResourceManager.GetString("EventDescSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programado cada {0} en {1} cada {2} empezando en {3}.
        /// </summary>
        internal static string EventScheduleDescRecurring {
            get {
                return ResourceManager.GetString("EventScheduleDescRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuración diaria tiene errores..
        /// </summary>
        internal static string ExcDailyConfig {
            get {
                return ResourceManager.GetString("ExcDailyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no puede ser un valor máximo de DateTime..
        /// </summary>
        internal static string ExcDateMaxValue {
            get {
                return ResourceManager.GetString("ExcDateMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no es una opción válida..
        /// </summary>
        internal static string ExcEnumError {
            get {
                return ResourceManager.GetString("ExcEnumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no es un valor de hora válido..
        /// </summary>
        internal static string ExcHoursValue {
            get {
                return ResourceManager.GetString("ExcHoursValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El siguiente evento fijado no está incluido entre los limites fijados..
        /// </summary>
        internal static string ExcLimits {
            get {
                return ResourceManager.GetString("ExcLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El limite final debe ser posterior al límite inicial..
        /// </summary>
        internal static string ExcLimitsEndBeforeStart {
            get {
                return ResourceManager.GetString("ExcLimitsEndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El día seleccionado debe estar entre 1-31.
        /// </summary>
        internal static string ExcMonthlyDay {
            get {
                return ResourceManager.GetString("ExcMonthlyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Configuración mensual seleccionada es incorrecta..
        /// </summary>
        internal static string ExcMonthlyTypeConfig {
            get {
                return ResourceManager.GetString("ExcMonthlyTypeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no tiene valor..
        /// </summary>
        internal static string ExcObjectNull {
            get {
                return ResourceManager.GetString("ExcObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} debe ser un número positivo..
        /// </summary>
        internal static string ExcPeriod {
            get {
                return ResourceManager.GetString("ExcPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primer.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuarto.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viernes.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to último.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lunes.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meses.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definido.
        /// </summary>
        internal static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sábado.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundo.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundos.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domingo.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tercer.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jueves.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to martes.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miércoles.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to día entre semana.
        /// </summary>
        internal static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to día de fin de semana.
        /// </summary>
        internal static string WeekendDay {
            get {
                return ResourceManager.GetString("WeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semanas.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to años.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
