//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration Error: {0}.
        /// </summary>
        public static string ConfError {
            get {
                return ResourceManager.GetString("ConfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a between {0} and {1}.
        /// </summary>
        public static string EventDescDailyLimits {
            get {
                return ResourceManager.GetString("EventDescDailyLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the day {0} of .
        /// </summary>
        public static string EventDescDayOfMonth {
            get {
                return ResourceManager.GetString("EventDescDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to {0}.
        /// </summary>
        public static string EventDescLimitsEnd {
            get {
                return ResourceManager.GetString("EventDescLimitsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a starting on {0}.
        /// </summary>
        public static string EventDescLimitsStart {
            get {
                return ResourceManager.GetString("EventDescLimitsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the {0} {1} of.
        /// </summary>
        public static string EventDescMonthlyPeriod {
            get {
                return ResourceManager.GetString("EventDescMonthlyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs once..
        /// </summary>
        public static string EventDescOnce {
            get {
                return ResourceManager.GetString("EventDescOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs every {0} {1}.
        /// </summary>
        public static string EventDescRecurring {
            get {
                return ResourceManager.GetString("EventDescRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a every {0} {1}.
        /// </summary>
        public static string EventDescRecurringEvery {
            get {
                return ResourceManager.GetString("EventDescRecurringEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a at {0}.
        /// </summary>
        public static string EventDescRecurringHour {
            get {
                return ResourceManager.GetString("EventDescRecurringHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs .
        /// </summary>
        public static string EventDescRecurringStart {
            get {
                return ResourceManager.GetString("EventDescRecurringStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a on {0}.
        /// </summary>
        public static string EventDescRecurringWeekly {
            get {
                return ResourceManager.GetString("EventDescRecurringWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schedule will be used on {0} at {1}.
        /// </summary>
        public static string EventDescSchedule {
            get {
                return ResourceManager.GetString("EventDescSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs every {0} on {1} every {2} starting on {3}.
        /// </summary>
        public static string EventScheduleDescRecurring {
            get {
                return ResourceManager.GetString("EventScheduleDescRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daily Frecuency configuration has errors..
        /// </summary>
        public static string ExcDailyConfig {
            get {
                return ResourceManager.GetString("ExcDailyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} can&apos;t be a Maximun DateTime value..
        /// </summary>
        public static string ExcDateMaxValue {
            get {
                return ResourceManager.GetString("ExcDateMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} hasn&apos;t be a valid option..
        /// </summary>
        public static string ExcEnumError {
            get {
                return ResourceManager.GetString("ExcEnumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ins&apos;t a valid Day Hour value..
        /// </summary>
        public static string ExcHoursValue {
            get {
                return ResourceManager.GetString("ExcHoursValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next schedule event isn&apos;t between date limits..
        /// </summary>
        public static string ExcLimits {
            get {
                return ResourceManager.GetString("ExcLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Limit should be after Start Limit. .
        /// </summary>
        public static string ExcLimitsEndBeforeStart {
            get {
                return ResourceManager.GetString("ExcLimitsEndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The day selected has to be in 1-31.
        /// </summary>
        public static string ExcMonthlyDay {
            get {
                return ResourceManager.GetString("ExcMonthlyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly Configuration selection isn&apos;t correct..
        /// </summary>
        public static string ExcMonthlyTypeConfig {
            get {
                return ResourceManager.GetString("ExcMonthlyTypeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} should be a Date value..
        /// </summary>
        public static string ExcNoDate {
            get {
                return ResourceManager.GetString("ExcNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Configuration Element hasn&apos;t got value..
        /// </summary>
        public static string ExcNull {
            get {
                return ResourceManager.GetString("ExcNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} hasn&apos;t got any value..
        /// </summary>
        public static string ExcObjectNull {
            get {
                return ResourceManager.GetString("ExcObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} should be a positive number..
        /// </summary>
        public static string ExcPeriod {
            get {
                return ResourceManager.GetString("ExcPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Defined.
        /// </summary>
        public static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
