//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: {0}.
        /// </summary>
        public static string ConfError {
            get {
                return ResourceManager.GetString("ConfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between {0} and {1}.
        /// </summary>
        public static string EventDescDailyLimits {
            get {
                return ResourceManager.GetString("EventDescDailyLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to {0}.
        /// </summary>
        public static string EventDescLimitsEnd {
            get {
                return ResourceManager.GetString("EventDescLimitsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting on {0}.
        /// </summary>
        public static string EventDescLimitsStart {
            get {
                return ResourceManager.GetString("EventDescLimitsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs once..
        /// </summary>
        public static string EventDescOnce {
            get {
                return ResourceManager.GetString("EventDescOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every {0} {1}.
        /// </summary>
        public static string EventDescRecurring {
            get {
                return ResourceManager.GetString("EventDescRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} {1}.
        /// </summary>
        public static string EventDescRecurringEvery {
            get {
                return ResourceManager.GetString("EventDescRecurringEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0}.
        /// </summary>
        public static string EventDescRecurringHour {
            get {
                return ResourceManager.GetString("EventDescRecurringHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        public static string EventDescRecurringWeekly {
            get {
                return ResourceManager.GetString("EventDescRecurringWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule will be used on {0} at {1}.
        /// </summary>
        public static string EventDescSchedule {
            get {
                return ResourceManager.GetString("EventDescSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every {0} on {1} every {2} starting on {3}.
        /// </summary>
        public static string EventScheduleDescRecurring {
            get {
                return ResourceManager.GetString("EventScheduleDescRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Frecuency configuration has errors..
        /// </summary>
        public static string ExcDailyConfig {
            get {
                return ResourceManager.GetString("ExcDailyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be a Maximun DateTime value..
        /// </summary>
        public static string ExcDateMaxValue {
            get {
                return ResourceManager.GetString("ExcDateMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hasn&apos;t be a valid option..
        /// </summary>
        public static string ExcEnumError {
            get {
                return ResourceManager.GetString("ExcEnumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next schedule event isn&apos;t between date limits..
        /// </summary>
        public static string ExcLimits {
            get {
                return ResourceManager.GetString("ExcLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Limit should be after Start Limit. .
        /// </summary>
        public static string ExcLimitsEndBeforeStart {
            get {
                return ResourceManager.GetString("ExcLimitsEndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a Date value..
        /// </summary>
        public static string ExcNoDate {
            get {
                return ResourceManager.GetString("ExcNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Configuration Element hasn&apos;t got value..
        /// </summary>
        public static string ExcNull {
            get {
                return ResourceManager.GetString("ExcNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hasn&apos;t got any value..
        /// </summary>
        public static string ExcObjectNull {
            get {
                return ResourceManager.GetString("ExcObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a positive number..
        /// </summary>
        public static string ExcPeriod {
            get {
                return ResourceManager.GetString("ExcPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Defined.
        /// </summary>
        public static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
